---
configmaps:

  - name: ngx-default.conf
    data: |+
      server {
          listen 80;
          server_name _;
          root /var/www/html;
          index index.html;

          location / {
              try_files $uri =404;
          }
          
          location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar|woff|woff2)$ {
              try_files $uri =404;
              expires max;
          }
      }