apiVersion: v1
kind: ConfigMap
metadata:
  name: pgdb-init
  namespace: 
data:
  createdb.sh: |
    #!/bin/sh

    psql << EOF

    CREATE USER $DBMIGRATION_USER WITH password '$DBMIGRATION_PASS';
    CREATE USER $DB_USER WITH password '$DB_PASS';
    CREATE USER $DBDEV_USER WITH password '$DBDEV_PASS';
    CREATE DATABASE $DB_NAME OWNER $DBMIGRATION_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DBMIGRATION_USER;
    GRANT CONNECT ON DATABASE $DB_NAME TO $DBDEV_USER;
    GRANT CONNECT ON DATABASE $DB_NAME TO $DB_USER;

    EOF

    psql -d $DB_NAME << EOF

    CREATE SCHEMA IF NOT EXISTS $TABLEFUNC_SCHEMA;
    GRANT USAGE ON SCHEMA $TABLEFUNC_SCHEMA TO $DB_USER;
    CREATE EXTENSION IF NOT EXISTS tablefunc SCHEMA $TABLEFUNC_SCHEMA;
    GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA $TABLEFUNC_SCHEMA TO $DB_USER;

    EOF

  loaddump.sh: |
    #!/bin/sh   

    pg_restore -d $DB_NAME /db-dumps/$DB_NAME.dump
    
  z_devUser.sh: |
    #!/bin/sh   
    
    psql -U $DBMIGRATION_USER -d $DB_NAME << EOF

    CREATE SCHEMA IF NOT EXISTS $DB_NAME;
    GRANT USAGE ON SCHEMA $DB_NAME TO $DBDEV_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_NAME GRANT SELECT ON TABLES TO $DBDEV_USER;

    EOF
