apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 
  namespace: 
spec:
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - name: 
        image: git-registry.sanscrit.kz/docker-images/postgres-alpine:0.0.1
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: pgdb-init
        - mountPath: /var/lib/postgresql/data
          name: pg-data        
      volumes:
      - name: pgdb-init
        configMap:
          name: pgdb-init
          items:
          - key: createdb.sh
            path: createdb.sh
      - name: pg-data
        hostPath:
          path:
