apiVersion: extensions/v1beta1
kind: Deployment  
metadata:
  name:
  namespace:
spec:  
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
      - image:
        name:     
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: myregistrykey


